name: Add to Milestone

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  milestonePR:
    if: github.repository_owner == 'AuroraEditor' && ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - name: Add pull request to Aurora Project Milestone 1
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PROJECT_ACCESS }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/AuroraEditor/AuroraEditor/issues/${{ github.event.pull_request.number }} \
          -d '{"milestone":1}'
  milestoneIssue:
    if: github.repository_owner == 'AuroraEditor' && ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - name: Add issue to Aurora Project Milestone 1
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/AuroraEditor/AuroraEditor/issues/${{ github.event.issue.number }} \
          -d '{"milestone":1}'
