name: Sync Main with Develop

on:
  schedule: ## Schedule the job to run at 12.am daily.
    - cron: '0 0 * * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: false
        name: Check last commit date
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  sync-branches:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup GitHub Env
        run: |
            git config --global user.name 'aurora-editor-bot'
            git config --global user.email 'aurora-editor-bot@users.noreply.github.com'
            git remote set-url --push origin https://aurora-editor-bot:$BOT_TOKEN@github.com/AuroraEditor/AuroraEditor
      
      - name: Sync with development
        run: |
            git merge development -m "Sync with development"
            git push origin main
